In [1]:
import sqlite3

In [2]:
conn=sqlite3.connect("std.db")
cursor=conn.cursor()
cursor.execute('''
    CREATE TABLE IF NOT EXISTS students (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        age INTEGER,
        grade TEXT
    )
''')
conn.commit()
print("table created successfully")

table created successfully


In [3]:
def insert_student(name, age, grade):
    cursor.execute("INSERT INTO students (name, age, grade) VALUES (?, ?, ?)", (name, age, grade))
    conn.commit()
    print("Student inserted successfully.")


insert_student('Riya', 20, 'A')
insert_student('Divyank', 22, 'B')

Student inserted successfully.
Student inserted successfully.


In [4]:
def fetch_students():
    cursor.execute("SELECT * FROM students")
    rows = cursor.fetchall()
    for row in rows:
        print(row)


fetch_students()

(1, 'Riya', 20, 'A')
(2, 'Divyank', 22, 'B')


In [5]:
def update_student(student_id, new_name, new_age, new_grade):
    cursor.execute("UPDATE students SET name=?, age=?, grade=? WHERE id=?", (new_name, new_age, new_grade, student_id))
    conn.commit()
    print("Student updated successfully.")
update_student(1, 'Riya Sharma', 21, 'A+')

Student updated successfully.


In [6]:
def delete_student(student_id):
    cursor.execute("DELETE FROM students WHERE id=?", (student_id,))
    conn.commit()
    print("Student deleted successfully.")


delete_student(2)

Student deleted successfully.


In [7]:
conn.close()
print("Database connection closed.")


Database connection closed.


In [11]:
import numpy as np

In [13]:
a=np.array([1,2,3])
b=np.array([[1,2],[3,4]])
print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [18]:
b=np.array([[1,2],[3,4]])
print(b.shape)
print(b.size)
print(b.ndim)
print(b.dtype)

(2, 2)
4
2
int64


In [21]:
a=np.array([1,2,3,4,5,6])
print(a.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [23]:
print(a[1])
print(a[1:4])

2
[2 3 4]


In [33]:
import numpy as np
a=np.array([1,2,3,4,5,6])
print(np.zeros((2,3)))
print(np.ones((2,3)))
print(np.eye((3)))
print(np.full((2,2),7))
print(np.arange(1,10,2))
print(np.linspace(1,5,4))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[7 7]
 [7 7]]
[1 3 5 7 9]
[1.         2.33333333 3.66666667 5.        ]


In [36]:
a=np.array([1,2,3,4,5,6,8])
b=np.array([1,2,3,4,5,6,7])
print(a+b)
print(a*b)
print(a**2)
print(np.sqrt(a))
print(np.mean(a))

[ 2  4  6  8 10 12 15]
[ 1  4  9 16 25 36 56]
[ 1  4  9 16 25 36 64]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.82842712]
4.142857142857143


In [41]:
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.sum(a,axis=0))

print(np.sort(a))
print(a.T)
print(a.flatten())

29
1
8
29
[1 2 3 4 5 6 8]
[1 2 3 4 5 6 8]
[1 2 3 4 5 6 8]


In [49]:
b=np.array([[1,2,3],[4,5,6]])
print(np.sum(b,axis=1))

[ 6 15]


In [51]:
a=np.array([[1,2],[3,4]])
a=np.array([[1,4],[2,4]])
print(np.dot(a,b))

[[17 22 27]
 [18 24 30]]


In [52]:
#Create a NumPy array of integers from 0 to 10.
a=np.array([0,1,2,3,4,5,6,7,8,9,10])
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [57]:
#Create an array of 10 zeros and change the 5th value to 1.
a=np.array([0,1,2,3,4,5,6,7,8,9,10])
a[4]=1
print(np.zeros((10)))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0  1  2  3  1  5  6  7  8  9 10]


In [58]:
#Generate an array of 10 ones.
print(np.ones((10)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [59]:
#Create a 1D array of 20 equally spaced numbers between 0 and 1.
a=np.array([0,1,2,3,4,5,6,7,8,9,10])
print(np.linspace(0, 1, 20))

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [60]:
#Create a 3x3 identity matrix.
i_matrix = np.identity(3)

print(i_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [61]:
#Create a 4x4 matrix with values from 0 to 15.
a=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(a.reshape(4, 4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [6]:
#Generate a 5x5 matrix with random values.
import numpy as np
b=np.random.randint(1, 101, size=(5,5))
print(b.size)
print(b.ndim)
print(b)

25
2
[[ 21  17  75  33  86]
 [ 75  47  90 100  18]
 [ 66  57  40  60  17]
 [ 20  94  96  67  89]
 [ 31   8  75  84  48]]


In [7]:
#Reverse the elements of an array.
a=np.array([[1,2],[3,4],[5,6]])
print(a.T)

[[1 3 5]
 [2 4 6]]


In [9]:
#Flatten a 2D array to 1D.
a=np.array([[1,2],[3,4]])
print(a.flatten())

[1 2 3 4]


In [18]:
#Extract even numbers from an array.
a=np.array([1,2,3,4])
even=a[a% 2 == 0]
print(even)

[2 4]
